# Borgmatic Configuration
# See: https://torsion.org/borgmatic/docs/reference/configuration/

source_directories:
  - /mnt/source/server
  - /mnt/source/world
  - /mnt/source/config

repositories:
  - path: /mnt/borg-repository/${CF_SLUG}

match_archives: "*"

keep_within: 2H
keep_hourly: 24
keep_daily: 14
keep_weekly: 12
keep_monthly: 12
keep_yearly: 999

exclude_patterns:
  - '/mnt/source/world/data/DistantHorizons.sqlite*'
